# Cloud Build configuration for User Management API
# Builds, tests, and deploys to Google Cloud Run

substitutions:
  _SERVICE_NAME: user-management-api
  _REGION: us-central1
  _INSTANCE_CONNECTION_NAME: ${PROJECT_ID}:${_REGION}:user-management-db

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

steps:
  # Step 1: Build the Docker image
  - id: 'build'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
      - '.'

  # Step 2: Push image to Container Registry
  - id: 'push'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
    waitFor: ['build']

  # Step 3: Push latest tag
  - id: 'push-latest'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
    waitFor: ['build']

  # Step 4: Run tests inside container
  - id: 'test'
    name: 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install pytest pytest-asyncio pytest-cov aiosqlite
        pytest tests/ -v --tb=short --junitxml=test-results.xml
    env:
      - 'DATABASE_URL=sqlite+aiosqlite:///:memory:'
      - 'ENVIRONMENT=testing'
      - 'SECRET_KEY=test-secret-key-for-cloud-build-testing-32ch'
    waitFor: ['push']

  # Step 5: Deploy to Cloud Run
  - id: 'deploy'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8000'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--concurrency'
      - '80'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'ENVIRONMENT=production,LOG_LEVEL=INFO,DEBUG=false'
      - '--set-secrets'
      - 'DATABASE_URL=database-url:latest,SECRET_KEY=secret-key:latest'
      - '--add-cloudsql-instances'
      - '${_INSTANCE_CONNECTION_NAME}'
    waitFor: ['test']

# Artifacts to store
artifacts:
  objects:
    location: 'gs://$PROJECT_ID-build-artifacts/${_SERVICE_NAME}/'
    paths:
      - 'test-results.xml'

# Images to be pushed
images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'

# Build timeout
timeout: '1800s'
